### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by romak12** [opencartbrasil/exibir-campos-personalizados#3]
When order customer and select 
![default](https://cloud.githubusercontent.com/assets/2143162/26510717/9283b3be-4256-11e7-973a-ddea90cf46ab.PNG)
admin info order show  :
![1](https://cloud.githubusercontent.com/assets/2143162/26510842/0b2fd5b8-4257-11e7-8992-035564c1d55d.PNG)
opencart 2.3.0.2

**Comment by o4itea** [comment]
Same issue

**Comment by ManoelVidal** [comment]
Could you please give me more details? @romak12 @o4itea

**Comment by Baraodosrelogios** [comment]
When changing the id in the url that displays the order history, requests from clients other than the one that is logged in are displayed
here:
index.php?route=account/order/info&order_id=11

**Comment by ManoelVidal** [comment]
@Baraodosrelogios resolved 👍

**Comment by ManoelVidal** [comment]
@romak12 I tested it here and the problem happened...
I'm providing the fix!
