### ISSUE TITLE
Incompatibilidade com 2.0.1.1

### ISSUE THREAD

**Issue by vynnus** [opencartbrasil/exibir-campos-personalizados#5]
Após atualização da última versão
é carregada uma página em branco ao clicar em Invoice
utilizando o OC 2.0.0.1

A versão anterior está funcionando mas tem o seguinte erro:
Tenho um campo personalizado chamado Complemento
Se este campo não foi preenchido aparece {custom_field_7}
na página do invoice.

**Comment by ManoelVidal** [comment]
Você está utilizando está versão?
https://github.com/opencartbrasil/exibir-campos-personalizados/releases/tag/v2.7.0-prior

**Comment by vynnus** [comment]
Não, baixei esta aí e corrigiu. Obrigado!
