### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/exibir-campos-personalizados#8]
Ao acessar a área para editar o endereço do cliente, no front-end, aparece o seguinte erro

PHP Warning:  Invalid argument supplied for foreach() system/storage/modification/catalog/controller/account/address.php na linha 191

Ocorre que não há dados preenchidos ainda nos campos Número e Complemento e causa o erro. Caso o usuário preencha, então não ocorre mais o erro.

**Comment by v5mvidal** [comment]
Resolvido na atualização para versão 3.1.1 liberada em 06/10/19
